# python run.py --method 'GraNDAG' --data_path "../data/ER-gauss-1000-400-800/0/data.csv" --groundtruth "../data/ER-gauss-1000-400-800/0/groundtruth.csv" --output "res/HCD_synthetic.csv" --datatype "continuous"
# python run.py --method 'GraNDAG' --data_path "../data/ER-gauss-1000-400-800/1/data.csv" --groundtruth "../data/ER-gauss-1000-400-800/1/groundtruth.csv" --output "res/HCD_synthetic.csv" --datatype "continuous"
# python run.py --method 'GraNDAG' --data_path "../data/ER-gauss-1000-400-800/2/data.csv" --groundtruth "../data/ER-gauss-1000-400-800/2/groundtruth.csv" --output "res/HCD_synthetic.csv" --datatype "continuous"

# python run.py --method 'GraNDAG' --data_path "../data/ER-gauss-1000-500-1000/0/data.csv" --groundtruth "../data/ER-gauss-1000-500-1000/0/groundtruth.csv" --output "res/HCD_synthetic.csv" --datatype "continuous"
# python run.py --method 'GraNDAG' --data_path "../data/ER-gauss-1000-500-1000/1/data.csv" --groundtruth "../data/ER-gauss-1000-500-1000/1/groundtruth.csv" --output "res/HCD_synthetic.csv" --datatype "continuous"
# python run.py --method 'GraNDAG' --data_path "../data/ER-gauss-1000-500-1000/2/data.csv" --groundtruth "../data/ER-gauss-1000-500-1000/2/groundtruth.csv" --output "res/HCD_synthetic.csv" --datatype "continuous"

# python run.py --method 'PC' --data_path "../data/win95pts/data_1000.csv" --groundtruth "../data/win95pts/graph.csv" --output "res/HCD_bnlearn.csv" --datatype "discrete" 
# python run.py --method 'PC' --data_path "../data/andes/data_1000.csv" --groundtruth "../data/andes/graph.csv" --output "res/HCD_bnlearn.csv" --datatype "discrete" 
# python run.py --method 'PC' --data_path "../data/diabetes/data_1000.csv" --groundtruth "../data/diabetes/graph.csv" --output "res/HCD_bnlearn.csv" --datatype "discrete" 
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/0/data.csv" --groundtruth "../data/andes-gauss-1000/0/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/1/data.csv" --groundtruth "../data/andes-gauss-1000/1/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/2/data.csv" --groundtruth "../data/andes-gauss-1000/2/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/3/data.csv" --groundtruth "../data/andes-gauss-1000/3/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/4/data.csv" --groundtruth "../data/andes-gauss-1000/4/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/5/data.csv" --groundtruth "../data/andes-gauss-1000/5/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/6/data.csv" --groundtruth "../data/andes-gauss-1000/6/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/7/data.csv" --groundtruth "../data/andes-gauss-1000/7/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/8/data.csv" --groundtruth "../data/andes-gauss-1000/8/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/andes-gauss-1000/9/data.csv" --groundtruth "../data/andes-gauss-1000/9/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"

python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/0/data.csv" --groundtruth "../data/win95pts-gauss-1000/0/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/1/data.csv" --groundtruth "../data/win95pts-gauss-1000/1/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/2/data.csv" --groundtruth "../data/win95pts-gauss-1000/2/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/3/data.csv" --groundtruth "../data/win95pts-gauss-1000/3/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/4/data.csv" --groundtruth "../data/win95pts-gauss-1000/4/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/5/data.csv" --groundtruth "../data/win95pts-gauss-1000/5/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/6/data.csv" --groundtruth "../data/win95pts-gauss-1000/6/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/7/data.csv" --groundtruth "../data/win95pts-gauss-1000/7/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/8/data.csv" --groundtruth "../data/win95pts-gauss-1000/8/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/win95pts-gauss-1000/9/data.csv" --groundtruth "../data/win95pts-gauss-1000/9/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"

# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/0/data.csv" --groundtruth "../data/diabetes-gauss-1000/0/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/1/data.csv" --groundtruth "../data/diabetes-gauss-1000/1/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/2/data.csv" --groundtruth "../data/diabetes-gauss-1000/2/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/3/data.csv" --groundtruth "../data/diabetes-gauss-1000/3/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/4/data.csv" --groundtruth "../data/diabetes-gauss-1000/4/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/5/data.csv" --groundtruth "../data/diabetes-gauss-1000/5/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/6/data.csv" --groundtruth "../data/diabetes-gauss-1000/6/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/7/data.csv" --groundtruth "../data/diabetes-gauss-1000/7/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/8/data.csv" --groundtruth "../data/diabetes-gauss-1000/8/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/diabetes-gauss-1000/9/data.csv" --groundtruth "../data/diabetes-gauss-1000/9/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"

# python run.py --method 'PC' --data_path "../data/link-gauss-1000/0/data.csv" --groundtruth "../data/link-gauss-1000/0/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/1/data.csv" --groundtruth "../data/link-gauss-1000/1/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/2/data.csv" --groundtruth "../data/link-gauss-1000/2/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/3/data.csv" --groundtruth "../data/link-gauss-1000/3/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/4/data.csv" --groundtruth "../data/link-gauss-1000/4/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/5/data.csv" --groundtruth "../data/link-gauss-1000/5/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/6/data.csv" --groundtruth "../data/link-gauss-1000/6/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/7/data.csv" --groundtruth "../data/link-gauss-1000/7/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/8/data.csv" --groundtruth "../data/link-gauss-1000/8/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/link-gauss-1000/9/data.csv" --groundtruth "../data/link-gauss-1000/9/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"

# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/0/data.csv" --groundtruth "../data/munin-gauss-1000/0/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/1/data.csv" --groundtruth "../data/munin-gauss-1000/1/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/2/data.csv" --groundtruth "../data/munin-gauss-1000/2/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/3/data.csv" --groundtruth "../data/munin-gauss-1000/3/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/4/data.csv" --groundtruth "../data/munin-gauss-1000/4/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/5/data.csv" --groundtruth "../data/munin-gauss-1000/5/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/6/data.csv" --groundtruth "../data/munin-gauss-1000/6/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/7/data.csv" --groundtruth "../data/munin-gauss-1000/7/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/8/data.csv" --groundtruth "../data/munin-gauss-1000/8/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
# python run.py --method 'PC' --data_path "../data/munin-gauss-1000/9/data.csv" --groundtruth "../data/munin-gauss-1000/9/groundtruth.csv" --output "res/HCD_semi_synthetic_oracle.csv" --datatype "continuous"
