python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/0/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/0/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/1/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/1/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/2/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/2/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/3/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/3/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/4/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/4/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/5/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/5/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/6/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/6/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/7/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/7/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/8/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/8/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/9/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/9/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic.csv" --datatype "continuous" --repeat 1
# python noRAM_CAPA.py --groundtruth_path "../data/andes-gauss-1000/0/groundtruth.csv" --data_path "../data/andes-gauss-1000/0/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic-1672025.csv" --datatype "continuous" --repeat 1
# python noRAM_CAPA.py --groundtruth_path "../data/diabetes-gauss-1000/0/groundtruth.csv" --data_path "../data/diabetes-gauss-1000/0/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic-1672025.csv" --datatype "continuous" --repeat 1
# python noRAM_CAPA.py --groundtruth_path "../data/link-gauss-1000/0/groundtruth.csv" --data_path "../data/link-gauss-1000/0/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic-1672025.csv" --datatype "continuous" --repeat 1
# python noRAM_CAPA.py --groundtruth_path "../data/munin-gauss-1000/0/groundtruth.csv" --data_path "../data/munin-gauss-1000/0/data.csv" --maxCset 2  --output "../res/CAPA-semi-synthetic-1672025.csv" --datatype "continuous" --repeat 1
