# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/0/data.csv" --groundtruth "../data/win95pts-gauss-1000/0/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/1/data.csv" --groundtruth "../data/win95pts-gauss-1000/1/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/2/data.csv" --groundtruth "../data/win95pts-gauss-1000/2/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/3/data.csv" --groundtruth "../data/win95pts-gauss-1000/3/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/4/data.csv" --groundtruth "../data/win95pts-gauss-1000/4/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/5/data.csv" --groundtruth "../data/win95pts-gauss-1000/5/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/6/data.csv" --groundtruth "../data/win95pts-gauss-1000/6/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/7/data.csv" --groundtruth "../data/win95pts-gauss-1000/7/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/8/data.csv" --groundtruth "../data/win95pts-gauss-1000/8/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/win95pts-gauss-1000/9/data.csv" --groundtruth "../data/win95pts-gauss-1000/9/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"

# python CPA.py --routine PC --data_path "../data/diabetes-gauss-1000/0/data.csv" --groundtruth "../data/diabetes-gauss-1000/0/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/diabetes-gauss-1000/1/data.csv" --groundtruth "../data/diabetes-gauss-1000/1/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/diabetes-gauss-1000/2/data.csv" --groundtruth "../data/diabetes-gauss-1000/2/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"

# python CPA.py --routine PC --data_path "../data/link-gauss-1000/0/data.csv" --groundtruth "../data/link-gauss-1000/0/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/link-gauss-1000/1/data.csv" --groundtruth "../data/link-gauss-1000/1/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/link-gauss-1000/2/data.csv" --groundtruth "../data/link-gauss-1000/2/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"

# python CPA.py --routine PC --data_path "../data/munin-gauss-1000/0/data.csv" --groundtruth "../data/munin-gauss-1000/0/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/munin-gauss-1000/1/data.csv" --groundtruth "../data/munin-gauss-1000/1/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
# python CPA.py --routine PC --data_path "../data/munin-gauss-1000/2/data.csv" --groundtruth "../data/munin-gauss-1000/2/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"

python CPA.py --routine PC --data_path "../data/link-gauss-1000/3/data.csv" --groundtruth "../data/link-gauss-1000/3/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
python CPA.py --routine PC --data_path "../data/link-gauss-1000/4/data.csv" --groundtruth "../data/link-gauss-1000/4/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
python CPA.py --routine PC --data_path "../data/link-gauss-1000/5/data.csv" --groundtruth "../data/link-gauss-1000/5/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
python CPA.py --routine PC --data_path "../data/link-gauss-1000/6/data.csv" --groundtruth "../data/link-gauss-1000/6/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
python CPA.py --routine PC --data_path "../data/link-gauss-1000/7/data.csv" --groundtruth "../data/link-gauss-1000/7/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
python CPA.py --routine PC --data_path "../data/link-gauss-1000/8/data.csv" --groundtruth "../data/link-gauss-1000/8/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
python CPA.py --routine PC --data_path "../data/link-gauss-1000/9/data.csv" --groundtruth "../data/link-gauss-1000/9/groundtruth.csv" --output "res/semi-synthetic-CPA.csv"
